server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.244.111:3306/menu?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

